/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.banBUS;
import DAO.dBConnection;
import DTO.banDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class GUIGopBan extends javax.swing.JDialog {

    /**
     * Creates new form GUIGopBan
     *
     * @param parent
     * @param modal
     */
    dBConnection db = new dBConnection();

    public GUIGopBan(java.awt.Frame parent, boolean modal) throws SQLException, ClassNotFoundException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
        cbBanGop1.setSelectedItem(Home.getBan());
        cbBanGop1.setEnabled(false);
    }

    public void loadData() {
        try {
            ArrayList<banDTO> list = banBUS.banAll();
            for (int i = 0; i < list.size(); i++) {
                cbBanGop1.addItem(list.get(i).getTenBan());
            }
            db.open();
            String sql = "SELECT * FROM ban WHERE TrangThai = 'Có khách'";
            ResultSet rs = db.excuteQuery(sql);
            while (rs.next()) {
                cBBanGop2.addItem(rs.getString("TenBan"));
            }
            db.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GUIChuyenBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbBanGop1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cBBanGop2 = new javax.swing.JComboBox<>();
        btnGop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chọn bàn cần gộp");

        btnGop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnGopBan.png"))); // NOI18N
        btnGop.setBorder(null);
        btnGop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGopActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gộp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbBanGop1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(cBBanGop2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGop))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBanGop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBBanGop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnGop)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGopActionPerformed
        try {
            String idBan = null;
            String sql = "Select IdBan from ban where TenBan = '" + cBBanGop2.getSelectedItem() + "'";
            db.open();
            ResultSet rs = db.excuteQuery(sql);
            while (rs.next()) {
                idBan = rs.getString("IdBan");
            }
            db.close();
            Home home = new Home();
            home.gopBan(idBan);
            Home.tabP.removeAll();
            home.loadBan();
            this.dispose();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GUIChuyenBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGopActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGop;
    private javax.swing.JComboBox<String> cBBanGop2;
    private javax.swing.JComboBox<String> cbBanGop1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
