/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.dBConnection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class GUILogin extends javax.swing.JFrame {

    int mouseX;
    int mouseY;
    public static String username;
    public static String name;
    public static String chucVu;
    public static String IdNhanVien;
    public static String gioiTinh;
    public GUILogin() {
        initComponents();
        txtUser.requestFocus();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        txtUser.setBackground(new Color(0,0,0,0));
        txtPass.setBackground(new Color(0,0,0,0));
        btnClose.setBackground(new Color(0,0,0,0));
        btnMinimize.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        errPass = new javax.swing.JLabel();
        errUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(95, 64, 42));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn.png"))); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setOpaque(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 150, -1));

        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setText("vanhoang01");
        txtPass.setBorder(null);
        txtPass.setOpaque(false);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 320, 40));

        btnMinimize.setBackground(new java.awt.Color(95, 64, 42));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_20px.png"))); // NOI18N
        btnMinimize.setBorder(null);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.setOpaque(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 30, 30));

        btnClose.setBackground(new java.awt.Color(95, 64, 42));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_25px_2.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 40, 30, 30));

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setText("Nhập Username");
        txtUser.setBorder(null);
        txtUser.setOpaque(false);
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 320, 40));

        errPass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        errPass.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(errPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 320, 20));

        errUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        errUser.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(errUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 234, 320, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (txtUser.getText().trim().isEmpty()) {
            errUser.setText("Vui lòng nhập username tài khoản!!!");
        }else if(txtPass.getText().trim().isEmpty()){
            errPass.setText("Vui lòng nhập mật khẩu!!!");
           
        }else if(txtUser.getText().trim().isEmpty() && txtPass.getText().trim().isEmpty()){
            errUser.setText("Vui lòng nhập username tài khoản!!!");
            errPass.setText("Vui lòng nhập mật khẩu!!!");
        }else{
            try {
                dBConnection db = new dBConnection();
                db.open();
            String sql = "SELECT * FROM user WHERE Username = ? AND Password = ?";
            PreparedStatement pts = db.conn.prepareStatement(sql);
            pts.setString(1, txtUser.getText());
            pts.setString(2, txtPass.getText());
            ResultSet rs = pts.executeQuery();
            if (rs.next()) {
                name = rs.getString("name");
                username = rs.getString("username");
                chucVu = rs.getString("chucvu");
                IdNhanVien = rs.getString("id");
                gioiTinh = rs.getString("gioitinh");
                Home home = new Home();
                home.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Tài khoản và mật khẩu không đúng!!! Xin thử lại!");
                txtPass.setText("");
                //txtUser.setText(saveUser);
            }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        txtUser.setText("");
    }//GEN-LAST:event_txtUserFocusGained

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        txtPass.setText("");
    }//GEN-LAST:event_txtPassFocusGained

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX,y - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLoginKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (txtUser.getText().trim().isEmpty()) {
                errUser.setText("Vui lòng nhập username tài khoản!!!");
            }else if(txtPass.getText().trim().isEmpty()){
                errPass.setText("Vui lòng nhập mật khẩu!!!");

            }else if(txtUser.getText().trim().isEmpty() && txtPass.getText().trim().isEmpty()){
                errUser.setText("Vui lòng nhập username tài khoản!!!");
                errPass.setText("Vui lòng nhập mật khẩu!!!");
            }else{
                try {
                    dBConnection db = new dBConnection();
                    db.open();
                String sql = "SELECT * FROM user WHERE Username = ? AND Password = ?";
                PreparedStatement pts = db.conn.prepareStatement(sql);
                pts.setString(1, txtUser.getText());
                pts.setString(2, txtPass.getText());
                ResultSet rs = pts.executeQuery();
                if (rs.next()) {
                    name = rs.getString("name");
                    username = rs.getString("username");
                    chucVu = rs.getString("chucvu");
                    IdNhanVien = rs.getString("id");
                    gioiTinh = rs.getString("gioitinh");
                    Home home = new Home();
                    home.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Tài khoản và mật khẩu không đúng!!! Xin thử lại!");
                    txtPass.setText("");
                }
                } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_txtPassKeyPressed
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JLabel errPass;
    private javax.swing.JLabel errUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void btnLoginActionPerformed(KeyEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
