/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.thucDonBUS;
import DAO.dBConnection;
import DAO.func;
import DTO.thucDonDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public final class GUIQuanLyThucDon extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    int flag;
    dBConnection db = new dBConnection();
    public GUIQuanLyThucDon() {
        initComponents();
        this.setSize(1350, 720);
        this.setLocationRelativeTo(null);
        loadThucDon();
        LoadComboBoxTT();
        LoadComboBoxTenLoaiThucDon();
        txtID.setEditable(false);
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);

    }
    //Show kết quả ra table
    public void loadThucDon() {
        try {
            ArrayList<thucDonDTO> list = thucDonBUS.thucDonAll();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] row = new Object[8];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getIdThucDon();
                row[1] = list.get(i).getTenLoaiThucDon();
                row[2] = list.get(i).getTenThucDon();
                row[3] = list.get(i).getDonViTinh();
                row[4] = list.get(i).getSoLuongTon();
                row[5] = list.get(i).getDonGiaTon();
                row[6] = list.get(i).getTonToiThieu();
                row[7] = list.get(i).getTrangThai();
                model.addRow(row);
            }
            dis_end(false);
            txtID.setEditable(false);
            btnXoa.setEnabled(false);
            btnSua.setEnabled(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void LoadComboBoxTT() {
        try {
            db.open();
            ResultSet rs = db.excuteQuery("SELECT TrangThai FROM `thucdon` GROUP BY TrangThai");
            while (rs.next()) {
                cBTrangThai.addItem(rs.getString("TrangThai"));
            }
        } catch (SQLException e) {
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void LoadComboBoxTenLoaiThucDon() {
        try {
            db.open();
            ResultSet rs = db.excuteQuery("SELECT TenLoaiThucDon FROM `loaithucdon` GROUP BY TenLoaiThucDon");
            while (rs.next()) {
                cBTenLoaiTD.addItem(rs.getString("TenLoaiThucDon"));
            }
        } catch (SQLException e) {
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void dis_end(boolean e) {
        txtTenTD.setEditable(e);
        txtSoLuongTon.setEditable(e);
        txtDonGiaTon.setEditable(e);
        txtDonViTinh.setEditable(e);
        txtTonToiThieu.setEditable(e);
        cBTrangThai.setEditable(e);
        cBTenLoaiTD.setEditable(e);
        btnHuy.setEnabled(e);
        btnLuu.setEnabled(e);
        btnSua.setEnabled(!e);
        btnThem.setEnabled(!e);
        btnXoa.setEnabled(!e);
    }

    public void SetNullText() {
        txtTenTD.setText("");
        txtSoLuongTon.setText("");
        txtDonGiaTon.setText("");
        txtDonViTinh.setText("");
        txtTonToiThieu.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textQlnv = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cBTenLoaiTD = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTenTD = new javax.swing.JTextField();
        txtDonViTinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSoLuongTon = new javax.swing.JTextField();
        txtDonGiaTon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTonToiThieu = new javax.swing.JTextField();
        cBTrangThai = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHẦN MỀM QUẢN LÝ QUÁN CAFFEE");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textQlnv.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        textQlnv.setText("QUẢN LÝ THỰC ĐƠN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tìm kiếm thực đơn: ");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTimKiem.setText("Nhập ID thực đơn / tên  thực đơn để tìm kiếm...");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setText("QUẢN LÝ THỰC ĐƠN");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel9.setText("DÁNH SÁCH THỰC ĐƠN");

        jLabel3.setText("ID THỰC ĐƠN: ");

        jLabel4.setText("TÊN LOẠI THỰC ĐƠN:");

        jLabel5.setText("TÊN THỰC ĐƠN: ");

        jLabel6.setText("ĐƠN VỊ TÍNH:");

        jLabel7.setText("SỐ LƯỢNG TỒN: ");

        txtDonGiaTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaTonActionPerformed(evt);
            }
        });

        jLabel10.setText("ĐƠN GIÁ TỒN: ");

        jLabel11.setText("TỒN TỐI THIỂU");

        jLabel12.setText("TRẠNG THÁI: ");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDThực Đơn", "Loại Thực Đơn", "Tên Thực Đơn", "Đơn Vị Tính", "Số Lượng Tồn", "Đơn Giá Tồn", "Tồn Tối thiểu", "Trạng thái"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(314, 314, 314))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(textQlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(686, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cBTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTonToiThieu)
                                    .addComponent(txtDonGiaTon)
                                    .addComponent(txtSoLuongTon)
                                    .addComponent(txtDonViTinh)
                                    .addComponent(txtID)
                                    .addComponent(cBTenLoaiTD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTenTD, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(textQlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cBTenLoaiTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTenTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDonGiaTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTonToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cBTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHuy)
                            .addComponent(btnLuu)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_home_filled_20px.png"))); // NOI18N
        jMenu1.setText("TRANG CHỦ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_system_information_20px.png"))); // NOI18N
        jMenu2.setText("HỆ THỐNG");

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_filled_20px.png"))); // NOI18N
        jMenu7.setText("Thông tin nhân viên");
        jMenu2.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_20px_1.png"))); // NOI18N
        jMenu8.setText("Đổi mật khẩu");
        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_manager_20px.png"))); // NOI18N
        jMenu3.setText("QUẢN LÝ");

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Organization_Chart_People_20px.png"))); // NOI18N
        jMenu13.setText("Quản lý nhân viên");
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu13MouseClicked(evt);
            }
        });
        jMenu13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu13);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Split_Table_20px.png"))); // NOI18N
        jMenu9.setText("Quản lý khu vực");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_restaurant_table_filled_20px.png"))); // NOI18N
        jMenu10.setText("Quản lý bàn");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu10);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_warehouse_20px.png"))); // NOI18N
        jMenu4.setText("KHO");

        jMenu11.setText("Quản lý loại thực đơn");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu11);

        jMenu12.setText("Quản lý thực đơn");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu12);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_list_15px.png"))); // NOI18N
        jMenu5.setText("THỐNG KÊ");
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_exit_15px.png"))); // NOI18N
        jMenu6.setText("ĐĂNG XUẤT");
        jMenuBar1.add(jMenu6);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_shutdown_20px_2.png"))); // NOI18N
        jMenu14.setText("THOÁT");
        jMenu14.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                jMenu14MenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenu14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu14MouseClicked(evt);
            }
        });
        jMenu14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu14ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtDonGiaTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaTonActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        func fabc = new func();
        try {
            txtID.setText(fabc.MaTuDong("IdThucDon", "thucdon", "TD"));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        flag = 0;
        dis_end(true);
        SetNullText();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        flag = 1;
        dis_end(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String query = "DELETE FROM `thucdon` WHERE IdThucDon = '" + txtID.getText() + "'";
        if (JOptionPane.showConfirmDialog(this, "Xóa thực đơn này?", "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                db.open();
                if (db.excuteUpdate(query) == 1) {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setNumRows(0);
                    loadThucDon();
                    JOptionPane.showMessageDialog(null, "Xóa thực đơn thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại!!!");
                }
                db.close();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
            }
            SetNullText();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        loadThucDon();
        dis_end(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (flag == 0) {
            //Thêm
            String query = "INSERT INTO `thucdon`( `IdThucDon`, `TenLoaiThucDon`, `TenThucDon`, `DonViTinh`, `SoLuongTon`, `DonGiaTon`,"
                    + " `TonToiThieu`, `TrangThai`) "
                    + "VALUES ('" + txtID.getText() + "','" + cBTenLoaiTD.getSelectedItem().toString() + "','" + txtTenTD.getText() + "','"
                    + txtDonViTinh.getText() + "','" + txtSoLuongTon.getText() + "','" + txtDonGiaTon.getText() + "','"
                    + txtTonToiThieu.getText() + "','" + cBTrangThai.getSelectedItem().toString() + "')";
            try {
                db.open();
                if (db.excuteUpdate(query) == 1) {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setNumRows(0);
                    loadThucDon();
                    JOptionPane.showMessageDialog(null, "Thêm thực đơn thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Thêm thất bại!!!");
                }
                db.close();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            //Sửa
            String query = "UPDATE `thucdon` "
                    + "SET `TenLoaiThucDon`='" + cBTenLoaiTD.getSelectedItem().toString() + "',`TenThucDon`='" + txtTenTD.getText() + "',"
                    + "`DonViTinh`='" + txtDonViTinh.getText() + "',`SoLuongTon`='" + txtSoLuongTon.getText() + "',"
                    + "`DonGiaTon`='" + txtDonGiaTon.getText() + "',`TonToiThieu`='" + txtTonToiThieu.getText() + "',"
                    + "`TrangThai`='" + cBTrangThai.getSelectedItem().toString() + "' WHERE `IdThucDon`='" + txtID.getText() + "'";
            try {
                db.open();
                if (db.excuteUpdate(query) == 1) {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setNumRows(0);
                    loadThucDon();
                    JOptionPane.showMessageDialog(null, "Cập nhật bàn thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Cập nhật thất bại!!!");
                }
                db.close();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
            }
            SetNullText();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        txtID.setText(model.getValueAt(i, 0).toString());
        cBTenLoaiTD.setSelectedItem(model.getValueAt(i, 1).toString());
        txtTenTD.setText(model.getValueAt(i, 2).toString());
        txtDonViTinh.setText(model.getValueAt(i, 3).toString());
        txtSoLuongTon.setText(model.getValueAt(i, 4).toString());
        txtDonGiaTon.setText(model.getValueAt(i, 5).toString());
        txtTonToiThieu.setText(model.getValueAt(i, 6).toString());
        cBTrangThai.setSelectedItem(model.getValueAt(i, 7).toString());
        dis_end(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu13MouseClicked
        GUIQuanLyNhanVien qlGUIQuanLyNhanVien = new GUIQuanLyNhanVien();
        qlGUIQuanLyNhanVien.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu13MouseClicked

    private void jMenu13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu13ActionPerformed

    }//GEN-LAST:event_jMenu13ActionPerformed

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        try {
            GUIQuanLyKhuVuc guiqlkv = new GUIQuanLyKhuVuc();
            guiqlkv.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        try {
            GUIQuanLyBan guiqlb = new GUIQuanLyBan();
            guiqlb.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked

        try {
            GUIQuanLyLoaiThucDon guiqlltd = new GUIQuanLyLoaiThucDon();
            guiqlltd.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        GUIQuanLyThucDon guiqltd = new GUIQuanLyThucDon();
        guiqltd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu14MenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu14MenuCanceled
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu14MenuCanceled

    private void jMenu14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu14MouseClicked

        if (JOptionPane.showConfirmDialog(this, "Bạn muốn thoát?", "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_jMenu14MouseClicked

    private void jMenu14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu14ActionPerformed

    }//GEN-LAST:event_jMenu14ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Home home = null;
        try {
            home = new Home();
        } catch (SQLException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        try {
            ArrayList<thucDonDTO> list = thucDonBUS.thucDonSearch(txtTimKiem.getText(), txtTimKiem.getText());
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);
            Object[] row = new Object[8];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getIdThucDon();
                row[1] = list.get(i).getTenLoaiThucDon();
                row[2] = list.get(i).getTenThucDon();
                row[3] = list.get(i).getDonViTinh();
                row[4] = list.get(i).getSoLuongTon();
                row[5] = list.get(i).getDonGiaTon();
                row[6] = list.get(i).getTonToiThieu();
                row[7] = list.get(i).getTrangThai();
                model.addRow(row);
            }
            dis_end(false);
            txtID.setEditable(false);
            btnXoa.setEnabled(false);
            btnSua.setEnabled(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIQuanLyThucDon().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cBTenLoaiTD;
    private javax.swing.JComboBox<String> cBTrangThai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel textQlnv;
    private javax.swing.JTextField txtDonGiaTon;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTenTD;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTonToiThieu;
    // End of variables declaration//GEN-END:variables
}
