/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.banBUS;
import DAO.dBConnection;
import DAO.func;
import DTO.banDTO;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public final class GUIQuanLyBan extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    int flag;
    dBConnection db = new dBConnection();

    public GUIQuanLyBan() throws ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        loadBan();
        LoadComboBoxKV();
        LoadComboBoxTT();
        txtID.setEditable(false);
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);

    }

    //Show kết quả ra table
    public void loadBan() throws ClassNotFoundException {
        ArrayList<banDTO> list = banBUS.banAll();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[5];
        banDTO ban = new banDTO();
        for (int i = 0; i < list.size(); i++) {
            ban = list.get(i);
            row[0] = ban.getIdBan();
            row[1] = ban.getTenKhuVuc();
            row[2] = ban.getTenBan();
            row[3] = ban.getDienGiai();
            row[4] = ban.getTrangThai();
            model.addRow(row);
        }
        dis_end_BAN(false);
        txtID.setEditable(false);
        btnXoa.setEnabled(false);
        btnSua.setEnabled(false);
    }

    public void LoadComboBoxTT() throws ClassNotFoundException {
        try {
            String sql = "SELECT TrangThai FROM `ban` GROUP BY TrangThai";
            db.open();
            ResultSet rs = db.excuteQuery(sql);
            while (rs.next()) {
                cBTrangThai.addItem(rs.getString("TrangThai"));
            }
            db.close();
        } catch (SQLException e) {
            db.displayError(e);
        }
    }
//Load ComboBox
    public void LoadComboBoxKV() throws ClassNotFoundException {
        try {
            db.open();
            ResultSet rs = db.excuteQuery("SELECT TenKhuVuc FROM `khuvuc` GROUP BY TenKhuVuc");
            while (rs.next()) {
                cBTenKhuVuc.addItem(rs.getString("TenKhuVuc"));
            }
            db.close();
        } catch (SQLException e) {
            db.displayError(e);
        }
    }
 //Enabled
    public void dis_end_BAN(boolean e) {
        txtTenBan.setEditable(e);
        txtDienGiai.setEditable(e);
        cBTrangThai.setEditable(e);
        btnHuy.setEnabled(e);
        btnLuu.setEnabled(e);
        btnSua.setEnabled(!e);
        btnThem.setEnabled(!e);
        btnXoa.setEnabled(!e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textQlnv = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        cBTenKhuVuc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDienGiai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cBTrangThai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnThemNhieu = new javax.swing.JButton();
        txtThemNhieu = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHẦN MỀM QUẢN LÝ QUÁN CAFFEE");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textQlnv.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        textQlnv.setText("QUẢN LÝ BÀN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tìm kiếm bàn: ");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTimKiem.setText("Nhập ID bàn / tên bàn để tìm kiếm...");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setText("QUẢN LÝ BÀN");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel9.setText("DANH SÁCH BÀN");

        jLabel3.setText("ID BÀN:");

        jLabel4.setText("TÊN KHU VỰC");

        jLabel5.setText("TÊN BÀN");

        txtTenBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenBanActionPerformed(evt);
            }
        });

        jLabel6.setText("DIỄN GIẢI: ");

        jLabel7.setText("TRẠNG THÁI");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDBAN", "TÊN KHU VỰC", "TÊN BÀN", "DIỄN GIẢI", "TRẠNG THÁI"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Thêm nhiều bàn: ");

        btnThemNhieu.setText("Thêm");
        btnThemNhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(textQlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtID)
                                            .addComponent(cBTenKhuVuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTenBan)
                                            .addComponent(txtDienGiai)
                                            .addComponent(cBTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtThemNhieu))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnThemNhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(91, 91, 91)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(340, 340, 340))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(textQlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cBTenKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDienGiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cBTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(btnLuu)
                            .addComponent(btnHuy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnThemNhieu)
                            .addComponent(txtThemNhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_home_filled_20px.png"))); // NOI18N
        jMenu1.setText("TRANG CHỦ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_system_information_20px.png"))); // NOI18N
        jMenu2.setText("HỆ THỐNG");

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_filled_20px.png"))); // NOI18N
        jMenu7.setText("Thông tin nhân viên");
        jMenu2.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_20px_1.png"))); // NOI18N
        jMenu8.setText("Đổi mật khẩu");
        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_manager_20px.png"))); // NOI18N
        jMenu3.setText("QUẢN LÝ");

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Organization_Chart_People_20px.png"))); // NOI18N
        jMenu13.setText("Quản lý nhân viên");
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu13MouseClicked(evt);
            }
        });
        jMenu13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu13);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Split_Table_20px.png"))); // NOI18N
        jMenu9.setText("Quản lý khu vực");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_restaurant_table_filled_20px.png"))); // NOI18N
        jMenu10.setText("Quản lý bàn");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu10);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_warehouse_20px.png"))); // NOI18N
        jMenu4.setText("KHO");

        jMenu11.setText("Quản lý loại thực đơn");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu11);

        jMenu12.setText("Quản lý thực đơn");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu12);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_list_15px.png"))); // NOI18N
        jMenu5.setText("THỐNG KÊ");
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_exit_15px.png"))); // NOI18N
        jMenu6.setText("ĐĂNG XUẤT");
        jMenuBar1.add(jMenu6);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_shutdown_20px_2.png"))); // NOI18N
        jMenu14.setText("THOÁT");
        jMenu14.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                jMenu14MenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenu14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu14MouseClicked(evt);
            }
        });
        jMenu14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu14ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTenBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenBanActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        func fabc = new func();
        try {
            txtID.setText(fabc.MaTuDong("IdBan", "ban", "BAN"));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtTenBan.setText("");
        txtDienGiai.setText("");
        flag = 0;
        dis_end_BAN(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        flag = 1;
        dis_end_BAN(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String query = "DELETE FROM `ban` WHERE IdBan = '" + txtID.getText() + "'";
        if (JOptionPane.showConfirmDialog(this, "Xóa bàn " + txtTenBan.getText() + "?", "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                db.open();
                if (db.excuteUpdate(query) == 1) {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setNumRows(0);
                    loadBan();
                    JOptionPane.showMessageDialog(null, "Xóa bàn thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại!!!");
                }
                db.close();
            } catch (SQLException | ClassNotFoundException ex) {
                db.displayError((SQLException) ex);
            }
            txtID.setText(null);
            txtTenBan.setText("");
            txtDienGiai.setText("");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (flag == 0) {
            //Thêm

            String query = "INSERT INTO `ban`( `IdBan`, `TenKhuVuc`, `TenBan`, `DienGiai`, `TrangThai`) "
                    + "VALUES ('" + txtID.getText() + "','" + cBTenKhuVuc.getSelectedItem().toString() + "','" + txtTenBan.getText()
                    + "','" + txtDienGiai.getText() + "','" + cBTrangThai.getSelectedItem().toString() + "')";
            try {
                db.open();
                if (db.excuteUpdate(query) == 1) {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setNumRows(0);
                    loadBan();
                    JOptionPane.showMessageDialog(null, "Thêm bàn thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Thêm thất bại!!!");
                }
                db.close();
            } catch (SQLException | ClassNotFoundException ex) {
                db.displayError((SQLException) ex);
            }

        } else {
            //Sửa
            String query = "UPDATE `ban` "
                    + "SET `TenKhuVuc`='" + cBTenKhuVuc.getSelectedItem().toString() + "',`TenBan`='" + txtTenBan.getText()
                    + "',`DienGiai`='" + txtDienGiai.getText() + "',`TrangThai`='" + cBTrangThai.getSelectedItem().toString() + "' "
                    + "WHERE IdBan = '" + txtID.getText() + "'";
            try {
                db.open();
                if (db.excuteUpdate(query) == 1) {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setNumRows(0);
                    loadBan();
                    JOptionPane.showMessageDialog(null, "Cập nhật bàn thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Cập nhật thất bại!!!");
                }
                db.close();
            } catch (SQLException | ClassNotFoundException ex) {
                db.displayError((SQLException) ex);
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            loadBan();
        } catch (ClassNotFoundException e) {
        }
        dis_end_BAN(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        txtID.setText(model.getValueAt(i, 0).toString());
        cBTenKhuVuc.setSelectedItem(model.getValueAt(i, 1).toString());
        txtTenBan.setText(model.getValueAt(i, 2).toString());
        txtDienGiai.setText(model.getValueAt(i, 3).toString());
        cBTrangThai.setSelectedItem(model.getValueAt(i, 4).toString());
        dis_end_BAN(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu13MouseClicked
        GUIQuanLyNhanVien qlGUIQuanLyNhanVien = new GUIQuanLyNhanVien();
        qlGUIQuanLyNhanVien.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu13MouseClicked

    private void jMenu13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu13ActionPerformed

    }//GEN-LAST:event_jMenu13ActionPerformed

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        try {
            GUIQuanLyKhuVuc guiqlkv = new GUIQuanLyKhuVuc();
            guiqlkv.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        try {
            GUIQuanLyBan guiqlb = new GUIQuanLyBan();
            guiqlb.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked

        try {
            GUIQuanLyLoaiThucDon guiqlltd = new GUIQuanLyLoaiThucDon();
            guiqlltd.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        GUIQuanLyThucDon guiqltd = new GUIQuanLyThucDon();
        guiqltd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu14MenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu14MenuCanceled
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu14MenuCanceled

    private void jMenu14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu14MouseClicked

        if (JOptionPane.showConfirmDialog(this, "Bạn muốn thoát?", "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_jMenu14MouseClicked

    private void jMenu14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu14ActionPerformed

    }//GEN-LAST:event_jMenu14ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        try {
            Home home = new Home();
            home.setVisible(true);
            this.setVisible(false);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        try {
            ArrayList<banDTO> list = banBUS.banSearch(txtTimKiem.getText(), txtTimKiem.getText());
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);
            Object[] row = new Object[5];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getIdBan();
                row[1] = list.get(i).getTenKhuVuc();
                row[2] = list.get(i).getTenBan();
                row[3] = list.get(i).getDienGiai();
                row[4] = list.get(i).getTrangThai();
                model.addRow(row);
            }
            dis_end_BAN(false);
            txtID.setEditable(false);
            btnXoa.setEnabled(false);
            btnSua.setEnabled(false);
        } catch (ClassNotFoundException e) {
        }


    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnThemNhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhieuActionPerformed
        try {
            int soLuong = (int) txtThemNhieu.getValue();
            if (soLuong > 0) {
                String sql = "SELECT * FROM `ban` ORDER BY `IdBan` DESC LIMIT 1";
                db.open();
                String tenBan = null;
                ResultSet rs = db.excuteQuery(sql);
                while (rs.next()) {
                    tenBan = rs.getString("TenBan");
                }
                db.close();
                String subID = tenBan.substring(4, tenBan.length());
                int a = Integer.parseInt(subID);
                String ban = "Bàn ";
                for (int i = 1; i <= soLuong; i++) {
                    int so = i + a;
                    String tenBanString = ban + so;
                    func fabc = new func();
                    try {
                        txtID.setText(fabc.MaTuDong("IdBan", "ban", "BAN"));
                    } catch (SQLException ex) {
                        Logger.getLogger(GUIQuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    String query = "INSERT INTO `ban`( `IdBan`, `TenKhuVuc`, `TenBan`, `DienGiai`, `TrangThai`) "
                            + "VALUES ('" + txtID.getText() + "','" + cBTenKhuVuc.getSelectedItem().toString() + "','" + tenBanString
                            + "','" + txtDienGiai.getText() + "','" + cBTrangThai.getSelectedItem().toString() + "')";
                    try {
                        db.open();
                        Statement st = db.conn.createStatement();
                        st.executeLargeUpdate(query);
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.setNumRows(0);
                        loadBan();
                        db.close();
                    } catch (SQLException ex) {
                        db.displayError(ex);
                    }
                }
                JOptionPane.showMessageDialog(null, "Thêm " + soLuong + " bàn thành công!!!");
            } else {
                JOptionPane.showMessageDialog(null, "Số lượng bàn là số âm hoặc bằng 0, Vui lòng nhập lại");
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIQuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnThemNhieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new GUIQuanLyBan().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIQuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemNhieu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cBTenKhuVuc;
    private javax.swing.JComboBox<String> cBTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel textQlnv;
    private javax.swing.JTextField txtDienGiai;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTenBan;
    private javax.swing.JSpinner txtThemNhieu;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
