/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.goiMonBUS;
import DTO.goiMonDTO;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class Print extends javax.swing.JDialog {

    /**
     * Creates new form Print
     */
    public Print(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        PrintHD();

    }

    public void PrintHD() {
        try {
            float tongTien = 0;
            Home h = new Home();
            ArrayList<goiMonDTO> list = goiMonBUS.goiMonIdBan(h.getIdBan(Home.tenBan));
            Date dt = new Date();
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd hh:mm");
            String thoiGian = s.format(dt);
            Area.append("\n"
                    + "\t\t   COFFEE & ACOUSTIC \n\n"
                    + "\n\t\t----------------------\n"
                    + "\t\t\tBIÊN LAI \n\n"
                    + "Thời gian: \t\t\t\t" + thoiGian + ""
                    + "\n=========================================================\n"
                    + "Mặt hàng:\t\t\t Số lượng \tSố tiền\n"
                    + "---------------------------------------------------------\n");

            for (int i = 0; i < list.size(); i++) {
                Area.append(list.get(i).getTenThucDon() + "\t\t\t\t" + list.get(i).getSoLuong() + "\t" + list.get(i).getThanhTien() + "\n");
                tongTien = tongTien + list.get(i).getThanhTien();
            }
            Area.append(
                    "\n"
                    + "---------------------------------------------------------\n"
                    + "Tổng tiền:\t\t\t\t\t" + tongTien + "đ\n"
                    + "---------------------------------------------------------\n"
                    + "\t Cảm ơn & chúc bạn một ngày tuyệt vời\n"
            );
//            Area.append(
//                    "\n"
//                    + "\t\t   COFFEE & ACOUSTIC \n\n"
//                    + "\n\t\t----------------------\n"
//                    + "\t\t\tBIÊN LAI \n\n"
//                    + "\n=========================================================\n"
//                    + "Mặt hàng:\t\t\t Số lượng \tSố tiền\n"
//                    + "---------------------------------------------------------\n"
//                    + "Mặt hàng:\t\t\t Số lượng \tSố tiền\n"
//                    + "Mặt hàng:\t\t\t Số lượng \tSố tiền\n"
//                    + "\n"
//                    + "---------------------------------------------------------\n"
//                    + "Tổng tiền: \t\t\t\t\t15000đ\n"
//                    + "---------------------------------------------------------\n"
//                    + "\t Cảm ơn & chúc bạn một ngày tuyệt vời\n"
//            );
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Print Preview");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 288, 10));

        Area.setColumns(20);
        Area.setRows(5);
        jScrollPane1.setViewportView(Area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, 570, 422));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 80, 40));

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Area.print();
            this.setVisible(false);
        } catch (PrinterException ex) {
            Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
